### ISSUE TITLE
replacement parameter has no effect

### ISSUE THREAD

**Issue by mpjashby** [hrbrmstr/slugify#1]
The `replacement` parameter in `slugify()` doesn't seem to have any effect:

``` r
library("slugify")

packageVersion("slugify")
#> [1] '0.1.0'

slugify("R is great!")
#> [1] "r-is-great"

slugify("R is great!", replacement = "_")
#> [1] "r-is-great"
```

<sup>Created on 2020-06-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Looking at the code for `slugify()`, `replacement = "-"` seems to be hard coded.

**Comment by hrbrmstr** [comment]
Shld work ok now.
